#!/bin/bash

GMAIL="jamesdouglassusa@gmail.com"
STANFORD="jdouglass@stanford.edu"

# Allows us to read user input below, assigns stdin to keyboard
# https://stackoverflow.com/a/10015707/299084
exec < /dev/tty

if git config --local user.email
then
    echo "Local address already set: $(git config --local user.email)"
else
    PS3='Please select the user.email address to use: '
    options=( $GMAIL $STANFORD )
    select opt in "${options[@]}"
    do
        case $opt in
            "$GMAIL")
                set -x
                git config --local user.email $GMAIL
                set +x
                break
                ;;
            "$STANFORD")
                set -x
                git config --local user.email $STANFORD
                set +x
                break
                ;;
            *) echo "invalid option $REPLY";;
        esac
    done
fi
